In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
plt.style.use(['dark_background'])

from keras.layers import Input, Dense, Flatten
from keras.models import Model
import keras
from keras.models import load_model
from sklearn.externals import joblib


scaler_filename = "scaler.save"


Using TensorFlow backend.
/usr/local/lib/python3.5/dist-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [2]:
# Load data
X_test = np.load('all_test.npy')
X_test_head = np.load('all_test_heads.npy')
sk2 = joblib.load(scaler_filename) 
X_test_head = sk2.transform(X_test_head)
#

In [3]:
X_test = X_test.reshape(-1,55*300)
X_test = (X_test-1)*1000
X_test = X_test.reshape(-1,55,300)


In [4]:
X_test.shape

(62900, 55, 300)

In [5]:
files = ['./weights/14_CV_weights_fold_3.h5',
'./weights/14_CV_weights_fold_5.h5',
# './weights/14_CV_weights_fold_7.h5',
# './weights/14_CV_weights_fold_8.h5',
# './weights/14_CV_weights_fold_9.h5',

#'./weights/15_CV_weights_fold_3.h5',
#'./weights/15_CV_weights_fold_5.h5',
#'./weights/15_CV_weights_fold_7.h5',
'./weights/15_CV_weights_fold_9.h5',

#'./weights/16_CV_weights_fold_1.h5',
'./weights/16_CV_weights_fold_3.h5',
#'./weights/16_CV_weights_fold_5.h5',
'./weights/16_CV_weights_fold_7.h5',
        
'./weights/20_CV_weights_fold_1.h5',
'./weights/20_CV_weights_fold_2.h5',
         
        
'./weights/21_CV_weights_fold_7.h5',
'./weights/21_CV_weights_fold_8.h5',
'./weights/21_CV_weights_fold_5.h5',
        ]

In [6]:
y_pred = np.zeros((X_test.shape[0], 55))
for whts_file in files:    
    print("FILE: ", whts_file)
    model = load_model(whts_file)
    y_pred+= model.predict([X_test,X_test_head])
y_pred/=len(files)
print("Done!")

W0808 13:49:49.625879 139998890268416 deprecation_wrapper.py:119] From /usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0808 13:49:49.645961 139998890268416 deprecation_wrapper.py:119] From /usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



FILE:  ./weights/14_CV_weights_fold_3.h5


W0808 13:49:49.886386 139998890268416 deprecation_wrapper.py:119] From /usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py:131: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0808 13:49:49.887154 139998890268416 deprecation_wrapper.py:119] From /usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0808 13:49:49.910576 139998890268416 deprecation.py:506] From /usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
W0808 13:49:50.446645 139998890268416 deprecation_wrapper.py:119] From /usr/local/lib/python3.5/dist-packages

FILE:  ./weights/14_CV_weights_fold_5.h5
FILE:  ./weights/15_CV_weights_fold_9.h5
FILE:  ./weights/16_CV_weights_fold_3.h5
FILE:  ./weights/16_CV_weights_fold_7.h5
FILE:  ./weights/20_CV_weights_fold_1.h5
FILE:  ./weights/20_CV_weights_fold_2.h5
FILE:  ./weights/21_CV_weights_fold_7.h5
FILE:  ./weights/21_CV_weights_fold_8.h5
FILE:  ./weights/21_CV_weights_fold_5.h5
Done!


In [8]:
# from scipy.stats.mstats import gmean

In [7]:
# y_pred_g = gmean(y_pred, axis=0)

In [7]:
y_pred[0]/1000

array([0.02440906, 0.02413466, 0.02550587, 0.02699541, 0.02611915,
       0.02824994, 0.02743189, 0.02807198, 0.02823898, 0.02799497,
       0.02789945, 0.02775083, 0.02769302, 0.02796322, 0.02861172,
       0.02951633, 0.02962845, 0.02984554, 0.03007035, 0.0299284 ,
       0.02985725, 0.02999538, 0.02978642, 0.02958915, 0.02929154,
       0.02921518, 0.02910897, 0.02931966, 0.02935668, 0.02964018,
       0.02973461, 0.03076544, 0.03184042, 0.03236644, 0.0319893 ,
       0.03209827, 0.03261211, 0.03177363, 0.03163695, 0.03140738,
       0.03078267, 0.03010935, 0.0295754 , 0.02904456, 0.0285091 ,
       0.02804202, 0.02776927, 0.02845776, 0.0292103 , 0.02966946,
       0.02982722, 0.03005857, 0.03043284, 0.03199106, 0.03239676])

In [7]:
y_pred[0]/1000

array([0.02442153, 0.0241946 , 0.02557162, 0.02701744, 0.02612668,
       0.02832622, 0.02748545, 0.02813334, 0.02834504, 0.02802921,
       0.0279588 , 0.02780891, 0.02774643, 0.0280027 , 0.0286719 ,
       0.02956966, 0.02973087, 0.02994227, 0.03015088, 0.02999325,
       0.0299652 , 0.02998825, 0.02984761, 0.02970307, 0.02934561,
       0.029299  , 0.02923821, 0.02934352, 0.02943504, 0.02969243,
       0.02981913, 0.03080725, 0.03188968, 0.03244645, 0.03202584,
       0.03219774, 0.03263061, 0.031815  , 0.03171884, 0.03146355,
       0.03085991, 0.03016737, 0.02963396, 0.02910292, 0.02856985,
       0.02809562, 0.02784874, 0.02850878, 0.0292275 , 0.02967809,
       0.02986728, 0.03016889, 0.03051102, 0.03207331, 0.03246659])

In [7]:
y_pred[0]/1000

array([0.02465564, 0.02440556, 0.02565924, 0.02706732, 0.02618154,
       0.02828642, 0.02748028, 0.02818855, 0.02831588, 0.02798807,
       0.02792743, 0.02770246, 0.02766213, 0.02800938, 0.02861786,
       0.02939211, 0.02965544, 0.02981832, 0.03003523, 0.02989155,
       0.02991761, 0.02991744, 0.02988987, 0.02972188, 0.02927591,
       0.02931223, 0.02923192, 0.02938369, 0.02940898, 0.02965951,
       0.02975373, 0.03055085, 0.0315454 , 0.03197556, 0.03171231,
       0.0318561 , 0.03227876, 0.03151348, 0.031382  , 0.03118423,
       0.0305518 , 0.02996447, 0.02938868, 0.02901708, 0.02846271,
       0.02811332, 0.02787431, 0.02845244, 0.02915194, 0.02960797,
       0.02979491, 0.03002757, 0.03049026, 0.03186254, 0.03217863])

In [18]:
y_pred[0]/1000

array([0.025733  , 0.02479542, 0.02658604, 0.02770169, 0.0267464 ,
       0.02961096, 0.02842712, 0.02964672, 0.02976619, 0.02871642,
       0.02786945, 0.02820771, 0.0287779 , 0.02884555, 0.02891708,
       0.03076033, 0.03051078, 0.03038514, 0.03158448, 0.03157462,
       0.03072883, 0.03131024, 0.031421  , 0.03221071, 0.03077694,
       0.03038606, 0.03013936, 0.02993738, 0.02989026, 0.03004852,
       0.03047293, 0.03139039, 0.0335306 , 0.03278215, 0.03314133,
       0.03398833, 0.03412612, 0.03320707, 0.03306318, 0.03315094,
       0.03187246, 0.03135222, 0.03044831, 0.03009218, 0.02992709,
       0.02907528, 0.02827338, 0.02923893, 0.03042822, 0.03078068,
       0.03071253, 0.03064258, 0.03053325, 0.0339225 , 0.03392957])

In [8]:
y_pred[3]/1000

array([0.02525634, 0.02498696, 0.0262715 , 0.02767223, 0.0267895 ,
       0.02890144, 0.02807688, 0.02877523, 0.02892782, 0.02859638,
       0.02853819, 0.02833187, 0.02829965, 0.02863769, 0.0292385 ,
       0.03000993, 0.03027161, 0.03041561, 0.03063943, 0.03048063,
       0.03051878, 0.03047883, 0.03044372, 0.0303267 , 0.02987525,
       0.02988464, 0.02983063, 0.02995295, 0.02997676, 0.03022683,
       0.03034931, 0.03115722, 0.03217307, 0.03259146, 0.03231491,
       0.03246097, 0.0328616 , 0.03213778, 0.03202484, 0.03180712,
       0.03117361, 0.03058726, 0.03001251, 0.02963211, 0.02907903,
       0.0287173 , 0.02849134, 0.0290767 , 0.02974649, 0.03019168,
       0.03036852, 0.0306168 , 0.03104258, 0.03243731, 0.03276543])

In [15]:
y_hat[3]

array([0.0270002 , 0.02639712, 0.02874242, 0.02943925, 0.02871528,
       0.03052872, 0.03082804, 0.03063677, 0.03113715, 0.03140564,
       0.03013091, 0.02996918, 0.03061048, 0.03113706, 0.03071937,
       0.03252496, 0.03193306, 0.03362761, 0.03282245, 0.03283552,
       0.03332335, 0.03236671, 0.03133969, 0.03170753, 0.03123524,
       0.03161856, 0.03176361, 0.03256135, 0.03217753, 0.03235571,
       0.03348286, 0.03136197, 0.03288736, 0.03413517, 0.03367416,
       0.03439772, 0.03460519, 0.03478727, 0.03369971, 0.03321015,
       0.03334809, 0.03266559, 0.03199422, 0.03179482, 0.03079639,
       0.02970411, 0.03007845, 0.03060967, 0.03236498, 0.03155456,
       0.03331548, 0.03260794, 0.03219257, 0.03385628, 0.03642869],
      dtype=float32)

In [20]:
y_hat[30]

array([ 0.04079049,  0.04206259, -0.02532413,  0.04489562,  0.02200453,
        0.03514845,  0.04327484,  0.04331911, -0.00113715,  0.0042902 ,
        0.04853427, -0.02700574,  0.04812065,  0.04199698, -0.01725069,
        0.03753296,  0.03982874, -0.02801515,  0.04141027,  0.04397069,
        0.03302779,  0.04330856, -0.01416363,  0.04726627,  0.04548471,
       -0.00204915,  0.01693093, -0.00690864,  0.04350819,  0.03405834,
        0.03924991, -0.01052146,  0.01962725,  0.04738668,  0.03455918,
        0.04179896,  0.03622829,  0.04073269,  0.04255065,  0.04057885,
        0.04466077, -0.02235563,  0.0458311 ,  0.03242953, -0.02721148,
        0.03461524, -0.01019617,  0.04747473,  0.04328866,  0.02407221,
       -0.01771915,  0.03646575,  0.04594073,  0.05187313,  0.03715964],
      dtype=float32)

In [8]:
np.savetxt('./sub/sub_21.csv', y_pred/1000)